service: editly-video-maker

plugins:
 - serverless-azure-functions
 - serverless-plugin-optimize
 - serverless-offline
 - serverless-plugin-typescript

provider:
  name: azure
  runtime: nodejs16
  region: ap-southeast-2
  stage: dev
  subscriptionId: cab43636-c1df-4c63-8837-f9c19790c9ea
  resourceGroup: DefaultResourceGroup-CUS

frameworkVersion: '3'

package:
  artifact: /.serverless/editly-video-maker.zip

  # Any `include`, `exclude` logic is applied to the whole service, the same
  # as built-in serverless packaging.
  # include: ...
  exclude:
    - "**/node_modules" # included on Lambda.a
    - "**/ffmpeg-layer"
    - "!package.json"

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
         method: ANY
         path: /
      - http: 
         method: ANY
         path: '{proxy+}'
    environment:
      FFMPEG_PATH: path/to/ffmpeg-binary
      FFPROBE_PATH: path/to/ffprobe-binary

# layers:
#   ffmpeg:
#     path: layer         